---
title: "IA Data by Schools (4) in AF Network"
author: "Ben Arancibia"
date: "November 12, 2014"
output: pdf_document
---
Read in the data

```{r}
UP <- read.csv(file="/Users/bcarancibia/DATA_eliza/UP.csv", head=TRUE, sep=",")
AMISTAD <- read.csv(file="/Users/bcarancibia/DATA_eliza/AMISTAD.csv",head=TRUE,sep=",")
HARTFORD <- read.csv(file="/Users/bcarancibia/DATA_eliza/HARTFORD.csv",head=TRUE,sep=",")
BHS <- read.csv(file="/Users/bcarancibia/DATA_eliza/BHS.csv",head=TRUE,sep=",")
```

Take a look at the summary information
```{r}
summary(UP)
summary(AMISTAD)
summary(HARTFORD)
summary(BHS)
```

The First column means nothing since it just a list of students.

Time to graph it
```{r}
require(ggplot2)

up_fig1 <- ggplot(UP, aes(x=Percentage)) + geom_histogram(aes(fill = ..count..))
amistad_fig1 <- ggplot(AMISTAD, aes(x=Percentage)) + geom_histogram(aes(fill = ..count..))
hartford_fig1 <- ggplot(HARTFORD, aes(x=Percentage)) + geom_histogram(aes(fill = ..count..))
bhs_fig1 <- ggplot(BHS, aes(x=Percentage)) + geom_histogram(aes(fill = ..count..))

up_fig1
amistad_fig1
hartford_fig1
bhs_fig1
```

You can see a lot from the data, what is most interesting is if you look at the actual shape of the curves
```{r}
up_fig2 <- ggplot(UP, aes(x=Percentage)) + geom_density()
amistad_fig2 <- ggplot(AMISTAD, aes(x=Percentage)) + geom_density()
hartford_fig2 <- ggplot(HARTFORD, aes(x=Percentage)) + geom_density()
bhs_fig2 <- ggplot(BHS, aes(x=Percentage)) + geom_density()

up_fig2
amistad_fig2
hartford_fig2
bhs_fig2

```



